version: '3.4'
services:
  db:
    image: paulormoj/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: 'test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    networks:
      - network
  rest-spring-boot:
    image: paulormoj/rest-spring-boot
    restart: always
    build: ./restspringboot
    working_dir: /restspringboot
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIROMENT: Production
    volumes:
      - ./restspringboot:/restspringboot
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
      - "8000:8000"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - network
networks:
  network:
      driver: bridge