version: "3.4"
services:
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "test"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    networks:
      - network
  rest-spring-boot:
    image: rest-spring-boot
    restart: always
    build: ./restspringboot
    working_dir: /restspringboot
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIROMENT: Production
    volumes:
      - ./restspringboot:/restspringboot
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - network
networks:
  network:
      driver: bridge