language: bash
services: docker
before_install:
  - cd restspringboot/
  - echo "Entramos no docker folder"
spript:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider:script
  script:
    docker push paulormoj/restspringboot;paulormoj/mysql;